name: Scrape PoGo Community Day

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/community_day.json
          git commit -m "[bot] Update Community Day data" || echo "No changes to commit"
          git push
